Solcast service
gewv-tu-dresden/tek-box-services pull request #10
Opened 2022-01-12 14:41 UTC by Malte96

- solcast-service auf Basis des ownServices erstellt
- Möglichkeit Vorgabe Zeitstempel aus Datenquelle für _send_data_message eingepflegt

2022-01-18 15:55 UTC, karlTGA requested changes
Some small issues. But all in all fine.

2022-01-18 15:55 UTC, karlTGA commented on tek_box_software/services/basic_service.py
> +        logger.info("create_measurement_tasks - basic")
please remove this comment

2022-01-18 15:55 UTC, karlTGA commented on tek_box_software/services/solcast/service.py
> +            for time in weather_data[request_type]:
is time really a good name for the entry in the data?

2022-01-18 15:55 UTC, karlTGA commented on tek_box_software/services/solcast/service.py
> +        self._host = None
What is that?

2022-01-19 08:54 UTC, Malte96 commented on tek_box_software/services/basic_service.py
> +        logger.info("create_measurement_tasks - basic")
I will take out, I have only missed this.

2022-01-19 08:55 UTC, Malte96 commented on tek_box_software/services/solcast/service.py
> +            for time in weather_data[request_type]:
I will find a better name.

2022-01-19 09:02 UTC, Malte96 commented on tek_box_software/services/solcast/service.py
> +        self._host = None
Not really necessary, was based on owm service.

2022-01-19 14:11 UTC, karlTGA approved these changes
only type, rest is fine

2022-01-19 14:11 UTC, karlTGA commented on tek_box_software/services/solcast/service.py
> +            for data_timestap in solcast_response_data[request_type]:
wat is a timestap? ^^

2022-01-19 14:16 UTC, Malte96 commented on tek_box_software/services/solcast/service.py
> +            for data_timestap in solcast_response_data[request_type]:
oh, awkward typo

2022-01-19 14:20 UTC, merged